### ISSUE TITLE
Is CenterNet2 also an anchor-free algorithm？

### ISSUE THREAD

**Issue by mucle** [xingyizhou/CenterNet2#18]
Please select an issue template from
https://github.com/facebookresearch/detectron2/issues/new/choose .

Otherwise your issue will be closed.

**Comment by xingyizhou** [comment]
Great question! In a narrow anchor definition, I would say yes, because we don't need to design the ratio/ size of anchors. However, in a broad anchor definition, it needs a fixed rule to assign objects to each FPN level, and does requires hyper-parameters about object sizes. Anyway, we can safely say the non-FPN version (i.e., stride 4) of CenterNet/ CenterNet2 is anchor-free (if that matters).

Best,
Xingyi
